"""restart_snapshot.py — mid-session restart-advisory snapshot (spec Inv 54).

A live Claude Code session loads its hooks, skills, subagents, settings, and
root CLAUDE.md ONCE at startup; any later on-disk change to those surfaces — a
`git pull`/merge, a manual edit, an IDE sync — leaves the running session
silently holding the stale copies. The `/rabbit-update install` marker (Inv 35b)
covers only the `install` command; this module adds a marker-free, deterministic
snapshot/re-check that fires the restart advisory for EVERY update path.

Mechanism:
  - SessionStart writes a content-hash signature of the restart-sensitive
    surface set to `<repo_root>/.rabbit-restart-snapshot` (the loaded baseline).
  - Stop / UserPromptSubmit recompute the signature and compare it to the
    snapshot; on a mismatch they surface ONE advisory print payload. They do
    NOT rewrite the snapshot, so the advisory persists across tick-ends until a
    fresh SessionStart re-baselines it.

Best-effort and graceful: any IO error degrades to no advisory (never crashes a
dispatcher).

Public API:
    restart_sensitive_signature(repo_root) -> dict[str, str]
    write_session_snapshot(repo_root) -> None
    restart_advisory_payloads(repo_root) -> list[dict]

Version: 1.1.0
Owner: rabbit-workflow team (rabbit-cage)
Deprecation criterion: when Claude Code reloads hooks/skills/agents in-session
    without a restart, making the stale-load advisory unnecessary.
"""

import datetime
import hashlib
import json
import os
from pathlib import Path

# The snapshot baseline file (relative to repo_root).
SNAPSHOT_FILE = ".rabbit-restart-snapshot"

# Inv 54c: the advisory line carries a wall-clock timestamp so the reader can
# judge freshness. The format matches the universal Stop turn-end timestamp
# (Inv 57): local wall-clock rendered as "%H:%M:%S %Z".
_TIMESTAMP_FMT = "%H:%M:%S %Z"

# Restart-sensitive surface set (spec Inv 54a): the on-disk artifacts a running
# session loads at startup and cannot reload without a restart. The same set
# scripts/rabbit-update.py enumerates for its install-path marker (Inv 35b).
_SENSITIVE_DIRS = (
    ".claude/hooks",
    ".claude/skills",
    ".claude/agents",
)
_SENSITIVE_FILES = ("CLAUDE.md",)

# The advisory line — deliberately distinct from the hard auto-resume banner so
# it reads as OPTIONAL (Inv 54c).
_ADVISORY_TEXT = (
    "restart ADVISED (not required): loaded skills/hooks/agents changed on "
    "disk — restart Claude Code to load the update"
)
_ADVISORY_ICON = "\U0001f504"  # 🔄


def _is_generated(p: Path) -> bool:
    """Generated bytecode under the monitored trees (`__pycache__/*.pyc`) is NOT
    a loaded artifact — importing the deployed hooks creates it mid-session, so
    including it would raise a spurious advisory. Exclude it."""
    return p.suffix == ".pyc" or "__pycache__" in p.parts


def _sensitive_paths(root: Path):
    """Enumerate existing restart-sensitive surfaces under `root`: every file in
    the hooks/skills/agents trees, every settings*.json under .claude/, and
    CLAUDE.md. Generated bytecode (`__pycache__/*.pyc`) is excluded. Only
    existing paths appear (an absent path is no change)."""
    paths = []
    for rel_dir in _SENSITIVE_DIRS:
        base = root / rel_dir
        if base.is_dir():
            paths.extend(
                p for p in base.rglob("*")
                if p.is_file() and not _is_generated(p))
    claude_dir = root / ".claude"
    if claude_dir.is_dir():
        paths.extend(p for p in claude_dir.glob("settings*.json") if p.is_file())
    for rel in _SENSITIVE_FILES:
        p = root / rel
        if p.is_file():
            paths.append(p)
    return paths


def restart_sensitive_signature(repo_root):
    """Map each existing restart-sensitive path (relative to repo_root) to a
    content sha256. A before/after diff of this map is the deterministic
    restart-required signal. Unreadable files are skipped (best-effort)."""
    root = Path(repo_root)
    sig = {}
    for p in _sensitive_paths(root):
        try:
            digest = hashlib.sha256(p.read_bytes()).hexdigest()
        except OSError:
            continue
        sig[str(p.relative_to(root))] = digest
    return sig


def write_session_snapshot(repo_root):
    """SessionStart baseline (Inv 54b): OVERWRITE the snapshot with the current
    restart-sensitive signature, recording what this session has loaded. A
    fresh SessionStart (a restart) re-baselines, clearing any prior advisory.
    Best-effort: an IO error is a silent no-op."""
    try:
        sig = restart_sensitive_signature(repo_root)
        (Path(repo_root) / SNAPSHOT_FILE).write_text(
            json.dumps(sig, sort_keys=True) + "\n")
    except OSError:
        return


def _read_snapshot(repo_root):
    path = Path(repo_root) / SNAPSHOT_FILE
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def restart_advisory_payloads(repo_root):
    """Stop / UserPromptSubmit re-check (Inv 54c): recompute the signature and
    compare to the snapshot. On a mismatch return the single advisory print
    payload; otherwise return []. The snapshot is NOT rewritten, so the advisory
    persists across tick-ends until a fresh SessionStart re-baselines it.

    Graceful: no snapshot (no prior SessionStart) → no advisory. Never raises.
    """
    baseline = _read_snapshot(repo_root)
    if baseline is None:
        return []
    current = restart_sensitive_signature(repo_root)
    if current == baseline:
        return []
    return [{"type": "print", "text": _advisory_text_with_timestamp(),
             "icon": _ADVISORY_ICON, "color": "green"}]


def _advisory_text_with_timestamp(now=None):
    """Inv 54c: the advisory text suffixed with ` (as of HH:MM:SS ZZZ)` so the
    reader can judge whether the alert is current or stale. The clock is LOCAL
    wall-clock with an explicit zone label (`%H:%M:%S %Z`) — the same format the
    universal Stop turn-end timestamp (Inv 57) uses, so the composite Stop block
    reads consistently. The optional `now` is an injected aware datetime for
    deterministic test rendering; the default is the real local clock (an aware
    local datetime so `%Z` populates with the real zone abbreviation)."""
    if now is None:
        now = datetime.datetime.now().astimezone()
    stamp = now.strftime(_TIMESTAMP_FMT).strip()
    return f"{_ADVISORY_TEXT} (as of {stamp})"
