"""restart_snapshot.py — mid-session restart-advisory snapshot (spec Inv 54).

A live Claude Code session loads its hooks, skills, subagents, settings, and
root CLAUDE.md ONCE at startup; any later on-disk change to those surfaces — a
`git pull`/merge, a manual edit, an IDE sync — leaves the running session
silently holding the stale copies. The `/rabbit-update install` marker (Inv 35b)
covers only the `install` command; this module adds a marker-free, deterministic
snapshot/re-check that fires the restart advisory for EVERY update path.

Mechanism:
  - SessionStart writes a content-hash signature of the restart-sensitive
    surface set to `<repo_root>/.rabbit-restart-snapshot` (the loaded baseline).
  - Stop / UserPromptSubmit recompute the signature and compare it to the
    snapshot; on a mismatch they surface ONE advisory print payload. They do
    NOT rewrite the snapshot, so the advisory persists across tick-ends until a
    fresh SessionStart re-baselines it.

Tiered remedy (spec Inv 54e): a full restart is not always required. Since
Claude Code v2.1.152 `/reload-skills` reloads `SKILL.md` definitions mid-session
without a restart, and skill `scripts/` are re-read on every invocation. So the
re-check classifies the SET of changed surfaces and emits the CHEAPEST
sufficient remedy: a `SKILL.md`-only change → a `/reload-skills` advisory; a
skill-`scripts/`-only change → nothing; any hook/settings/CLAUDE.md/agent change
→ the full-restart advisory; mixed → the superset (strongest remedy) wins
(strict precedence full-restart > reload-skills > nothing).

Best-effort and graceful: any IO error degrades to no advisory (never crashes a
dispatcher).

Mid-session reload re-baseline (spec Inv 54f): the SessionStart re-baseline above
is the ONLY thing that clears the snapshot, so the reload-tier advisory would
otherwise fire forever. `/reload-skills` reloads `SKILL.md` definitions
mid-session but is a Claude Code CLIENT-LOCAL built-in that NEVER fires the
UserPromptSubmit hook, so it cannot drive the re-baseline (a prior fix that
matched the `/reload-skills` submitted prompt was wiring a DEAD path — #1193).
The clearing surface is instead the `/rabbit-refresh` command: its body runs
`scripts/rabbit-refresh-rebaseline.py`, which calls `rebaseline_skill_tier` to
refresh ONLY the `SKILL.md`-tier keys of the snapshot (so the reload-tier
advisory clears) while leaving the hard-restart-tier keys
(hooks/settings/CLAUDE.md/agents) untouched — a genuine hard-restart change still
legitimately requires a restart. So the advisory text directs the user to
`/reload-skills` to load the change AND `/rabbit-refresh` to dismiss the advisory.

Public API:
    restart_sensitive_signature(repo_root) -> dict[str, str]
    write_session_snapshot(repo_root) -> None
    restart_advisory_payloads(repo_root) -> list[dict]
    rebaseline_skill_tier(repo_root) -> None

Version: 1.5.0
Owner: rabbit-workflow team (rabbit-cage)
Deprecation criterion: when Claude Code reloads hooks/skills/agents in-session
    without a restart, making the stale-load advisory unnecessary.
"""

import datetime
import hashlib
import json
import os
from pathlib import Path

# The snapshot baseline file (relative to repo_root).
SNAPSHOT_FILE = ".rabbit-restart-snapshot"

# Inv 54c: the advisory line carries a wall-clock timestamp so the reader can
# judge freshness. The format matches the universal Stop turn-end timestamp
# (Inv 57): local wall-clock rendered as "%H:%M:%S %Z".
_TIMESTAMP_FMT = "%H:%M:%S %Z"

# Restart-sensitive surface set (spec Inv 54a): the on-disk artifacts a running
# session loads at startup and cannot reload without a restart. The same set
# scripts/rabbit-update.py enumerates for its install-path marker (Inv 35b).
_SENSITIVE_DIRS = (
    ".claude/hooks",
    ".claude/skills",
    ".claude/agents",
)
_SENSITIVE_FILES = ("CLAUDE.md",)

# The full-restart advisory line — deliberately distinct from the hard
# auto-resume banner so it reads as OPTIONAL (Inv 54c).
_ADVISORY_TEXT = (
    "restart ADVISED (not required): loaded skills/hooks/agents changed on "
    "disk — restart Claude Code to load the update"
)
_ADVISORY_ICON = "\U0001f504"  # 🔄

# The cheaper reload advisory line (Inv 54e) for a SKILL.md-only change:
# `/reload-skills` reloads skill definitions mid-session without a restart, and
# `/rabbit-refresh` dismisses this advisory (Inv 54f) — `/reload-skills` is a
# client-local built-in that cannot clear it (#1193).
_RELOAD_ADVISORY_TEXT = (
    "reload ADVISED (not required): skill definitions changed on disk — run "
    "/reload-skills to load the update, then /rabbit-refresh to dismiss this "
    "(no restart needed)"
)


def _is_generated(p: Path) -> bool:
    """Generated bytecode under the monitored trees (`__pycache__/*.pyc`) is NOT
    a loaded artifact — importing the deployed hooks creates it mid-session, so
    including it would raise a spurious advisory. Exclude it."""
    return p.suffix == ".pyc" or "__pycache__" in p.parts


def _sensitive_paths(root: Path):
    """Enumerate existing restart-sensitive surfaces under `root`: every file in
    the hooks/skills/agents trees, every settings*.json under .claude/, and
    CLAUDE.md. Generated bytecode (`__pycache__/*.pyc`) is excluded. Only
    existing paths appear (an absent path is no change)."""
    paths = []
    for rel_dir in _SENSITIVE_DIRS:
        base = root / rel_dir
        if base.is_dir():
            paths.extend(
                p for p in base.rglob("*")
                if p.is_file() and not _is_generated(p))
    claude_dir = root / ".claude"
    if claude_dir.is_dir():
        paths.extend(p for p in claude_dir.glob("settings*.json") if p.is_file())
    for rel in _SENSITIVE_FILES:
        p = root / rel
        if p.is_file():
            paths.append(p)
    return paths


def restart_sensitive_signature(repo_root):
    """Map each existing restart-sensitive path (relative to repo_root) to a
    content sha256. A before/after diff of this map is the deterministic
    restart-required signal. Unreadable files are skipped (best-effort)."""
    root = Path(repo_root)
    sig = {}
    for p in _sensitive_paths(root):
        try:
            digest = hashlib.sha256(p.read_bytes()).hexdigest()
        except OSError:
            continue
        sig[str(p.relative_to(root))] = digest
    return sig


def write_session_snapshot(repo_root):
    """SessionStart baseline (Inv 54b): OVERWRITE the snapshot with the current
    restart-sensitive signature, recording what this session has loaded. A
    fresh SessionStart (a restart) re-baselines, clearing any prior advisory.
    Best-effort: an IO error is a silent no-op."""
    try:
        sig = restart_sensitive_signature(repo_root)
        (Path(repo_root) / SNAPSHOT_FILE).write_text(
            json.dumps(sig, sort_keys=True) + "\n")
    except OSError:
        return


def _read_snapshot(repo_root):
    path = Path(repo_root) / SNAPSHOT_FILE
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def rebaseline_skill_tier(repo_root):
    """Inv 54f: re-baseline ONLY the `SKILL.md`-tier keys of the snapshot.

    Invoked by `scripts/rabbit-refresh-rebaseline.py` (the `/rabbit-refresh`
    command's companion script) — the corrected clearing surface, since
    `/reload-skills` is a Claude Code client-local built-in that never reaches a
    hook (#1193). After the user reloads skills the running session holds the
    current on-disk skill definitions, so the reload-tier advisory must clear:
    refresh every `SKILL.md` key (current vs absent) in the snapshot to its
    current digest, but leave the hard-restart-tier keys (hooks / settings /
    CLAUDE.md / agents) and the skill-`scripts/` keys EXACTLY as they were, so a
    genuine hard-restart change still legitimately fires its advisory.

    Surgical: SKILL.md keys present on disk are set to their current sha256;
    SKILL.md keys that vanished from disk are dropped from the snapshot. No
    other key is touched. Best-effort: no snapshot, or any IO error, is a
    silent no-op (never crashes the dispatcher)."""
    baseline = _read_snapshot(repo_root)
    if baseline is None:
        return
    current = restart_sensitive_signature(repo_root)
    updated = dict(baseline)
    # Refresh / drop every SKILL.md key — across both the snapshot and the
    # current on-disk signature — to the now-loaded state.
    for key in set(baseline) | set(current):
        if not _is_skill_md(key):
            continue
        if key in current:
            updated[key] = current[key]
        else:
            updated.pop(key, None)
    try:
        (Path(repo_root) / SNAPSHOT_FILE).write_text(
            json.dumps(updated, sort_keys=True) + "\n")
    except OSError:
        return


def _is_skill_md(rel: str) -> bool:
    """A `.claude/skills/**/SKILL.md` path — reloadable via `/reload-skills`
    without a restart (Inv 54e)."""
    return rel.startswith(".claude/skills/") and Path(rel).name == "SKILL.md"


def _is_skill_script(rel: str) -> bool:
    """A `.claude/skills/` path that is NOT a `SKILL.md` (a skill `scripts/`
    file) — re-read on the next invocation, so no remedy is needed (Inv 54e)."""
    return rel.startswith(".claude/skills/") and Path(rel).name != "SKILL.md"


def _classify_remedy(changed_keys):
    """Inv 54e: map the SET of changed restart-sensitive relative paths to the
    cheapest sufficient remedy. Strict precedence: full-restart > reload-skills
    > nothing.

      - any non-skill surface changed (hook / settings / CLAUDE.md / agent) →
        "restart" (a full restart is required).
      - else any SKILL.md changed → "reload" (/reload-skills suffices).
      - else (only skill scripts/ changed, or nothing) → None (no remedy).
    """
    has_hard = any(
        not (_is_skill_md(k) or _is_skill_script(k)) for k in changed_keys)
    if has_hard:
        return "restart"
    if any(_is_skill_md(k) for k in changed_keys):
        return "reload"
    return None


def restart_advisory_payloads(repo_root):
    """Stop / UserPromptSubmit re-check (Inv 54c/54e): recompute the signature,
    compare to the snapshot, and return the CHEAPEST sufficient advisory print
    payload for the set of changed surfaces — the full-restart advisory, the
    `/reload-skills` advisory, or none. The snapshot is NOT rewritten, so the
    advisory persists across tick-ends until a fresh SessionStart re-baselines.

    Graceful: no snapshot (no prior SessionStart) → no advisory. Never raises.
    """
    baseline = _read_snapshot(repo_root)
    if baseline is None:
        return []
    current = restart_sensitive_signature(repo_root)
    # The changed set = keys whose digest differs, plus keys added or removed.
    changed_keys = {
        k for k in set(baseline) | set(current)
        if baseline.get(k) != current.get(k)
    }
    if not changed_keys:
        return []
    remedy = _classify_remedy(changed_keys)
    if remedy == "restart":
        text = _ADVISORY_TEXT
    elif remedy == "reload":
        text = _RELOAD_ADVISORY_TEXT
    else:
        return []
    return [{"type": "print", "text": _advisory_text_with_timestamp(text),
             "icon": _ADVISORY_ICON, "color": "yellow"}]


def _advisory_text_with_timestamp(base_text=_ADVISORY_TEXT, now=None):
    """Inv 54c: the advisory text suffixed with ` (as of HH:MM:SS ZZZ)` so the
    reader can judge whether the alert is current or stale. The clock is LOCAL
    wall-clock with an explicit zone label (`%H:%M:%S %Z`) — the same format the
    universal Stop turn-end timestamp (Inv 57) uses, so the composite Stop block
    reads consistently. `base_text` is the tier-specific advisory line (full
    restart or /reload-skills, Inv 54e). The optional `now` is an injected aware
    datetime for deterministic test rendering; the default is the real local
    clock (an aware local datetime so `%Z` populates with the real zone
    abbreviation)."""
    if now is None:
        now = datetime.datetime.now().astimezone()
    stamp = now.strftime(_TIMESTAMP_FMT).strip()
    return f"{base_text} (as of {stamp})"
