#!/usr/bin/env python3
"""run.py — run all contract feature tests in sequence.

Non-interactive. Exits non-zero on first failure. Per Inv 17, this runner
MUST invoke every active test-*.py file in this directory.
"""

import os
import sys
import subprocess

TEST_DIR = os.path.dirname(os.path.abspath(__file__))


def run_test(script):
    print(f"=== {script} ===")
    result = subprocess.run(
        ["python3", os.path.join(TEST_DIR, script)]
    )
    if result.returncode != 0:
        print(f"--- FAIL: {script} ---", file=sys.stderr)
        sys.exit(result.returncode)
    print(f"--- PASS: {script} ---")
    print()


run_test("test-files-exist.py")
run_test("test-policy-block.py")
run_test("test-policy-block-lib.py")
run_test("test-build-prompt.py")
run_test("test-templates-have-version.py")
run_test("test-templates-prompts-bundle.py")
run_test("test-prompt-tdd-subagent-has-8-steps.py")
run_test("test-schemas-valid-json.py")
run_test("test-publish-manifest-schema.py")
run_test("test-validate-no-bugs-root.py")
run_test("test-validate-feature-real-features.py")
run_test("test-spec-path-dual-read.py")
run_test("test-skill-command-templates.py")
run_test("test-rabbit-print-renderer.py")
run_test("test-rabbit-block-assembler.py")
run_test("test-check-naming-bans-rbt.py")
run_test("test-python-only-stack.py")
run_test("test-cli-naming-convention.py")
run_test("test-check-tests-non-interactive.py")
run_test("test-find-feature.py")
run_test("test-validate-feature-runner-python.py")
run_test("test-contract-scripts-have-docstrings.py")
run_test("test-run-invokes-all-active-tests.py")
run_test("test-retired-artifacts.py")
run_test("test-feature-schema-permissive.py")
run_test("test-template-schema-producer-live-refs.py")
run_test("test-check-sentinel-scans-py.py")
run_test("test-feature-template-validates-schema.py")
run_test("test-find-feature-scope-and-handles.py")
run_test("test-find-feature-plugin-mode.py")
run_test("test-check-symlinks-deep.py")
run_test("test-check-imports-resolve-surface-dirs.py")
run_test("test-workspace-structure-naming.py")
run_test("test-bug-fixes-cycle.py")
run_test("test-workspace-declares-all-features.py")
run_test("test-check-numbered-lists.py")
run_test("test-check-prompts-section.py")
run_test("test-check-prompts-section-live.py")
run_test("test-no-dead-contract-scripts.py")
run_test("test-no-subagent-launch-template.py")
run_test("test-retirement-semantics.py")
run_test("test-lib-checks.py")
run_test("test-rabbit-feature-skills-deployment.py")
run_test("test-check-invariant-monotonic-order.py")
run_test("test-changelog-exists.py")
run_test("test-manifest-schema-shape.py")
run_test("test-runtime-schema-shape.py")
run_test("test-configuration-schema-shape.py")
run_test("test-prompts-schema-shape.py")
run_test("test-project-map-schema-shape.py")
run_test("test-feature-json-schema-admits-meta-contract.py")
run_test("test-validate-meta-contract-manifest.py")
run_test("test-validate-meta-contract-runtime.py")
run_test("test-validate-meta-contract-configuration.py")
run_test("test-validate-meta-contract-prompts.py")
run_test("test-validate-meta-contract-cli.py")
run_test("test-publish-file.py")
run_test("test-publish-skill-command-agent.py")
run_test("test-publish-hook.py")
run_test("test-publish-settings.py")
run_test("test-publish-generated.py")
run_test("test-mutation-write-marker.py")
run_test("test-mutation-delete-marker.py")
run_test("test-mutation-set-json-key.py")
run_test("test-mutation-delete-json-key.py")
run_test("test-mutation-append-json-array.py")
run_test("test-mutation-remove-json-array-value.py")
run_test("test-mutation-run-feature-script.py")
run_test("test-producers-dispatch.py")
run_test("test-producers-read-file.py")
run_test("test-producers-expand-at-imports.py")
run_test("test-producers-generate-claude-md.py")
run_test("test-producers-publish-generated-integration.py")
run_test("test-runtime-result-helpers.py")
run_test("test-runtime-check-marker-alert.py")
run_test("test-runtime-check-marker-consume-alert.py")
run_test("test-runtime-check-counter-threshold-refresh.py")
run_test("test-runtime-welcome-with-policy.py")
run_test("test-runtime-check-drift-regenerate.py")
run_test("test-runtime-check-drift-regenerate-real-producer.py")
run_test("test-runtime-check-manifest-drift.py")
run_test("test-runtime-check-manifest-drift-walks-all-entries.py")
run_test("test-runtime-iterate-configurables-alerts.py")
run_test("test-runtime-iterate-configurables-banner.py")
run_test("test-runtime-emit-configurable-alert.py")
run_test("test-runtime-cleanup-old-prompts.py")
run_test("test-runtime-check-prompt-injection-failures.py")
run_test("test-runtime-write-mode-marker.py")
run_test("test-runtime-check-release-update.py")
run_test("test-runtime-emit-auto-evolve-banner.py")
run_test("test-runtime-emit-auto-evolve-stop-line.py")
run_test("test-runtime-emit-stop-timestamp.py")
run_test("test-check-release-update-helper.py")
run_test("test-spec-bodies-no-historical-tags.py")
run_test("test-runtime-api-enum-sourced-from-schema.py")
run_test("test-templates-validate-against-schemas.py")
run_test("test-deployed-skills-match-source.py")
run_test("test-publish-file-deployed-copies-match-source.py")
run_test("test-validate-agent-prompt-sentinel.py")
run_test("test-retirement-skill-injection.py")

print("ALL TESTS PASSED")
