#!/usr/bin/env python3
"""test-publish-generated.py — exercises publish_generated: invokes a named
content producer and writes its output to target (idempotent on content).

lib.producers is not yet written (Plan B.4). This test stubs it via
sys.modules injection BEFORE importing lib.publish so the lazy import inside
publish_generated resolves to the stub.
"""

import os
import sys
import tempfile
import types

FEATURE_DIR = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, FEATURE_DIR)

# Stub lib.producers BEFORE importing lib.publish.
_producers_stub = types.ModuleType("lib.producers")
_producers_stub.call_producer = lambda name, args, feature_dir, repo_root: f"# generated by {name}\n"
sys.modules["lib.producers"] = _producers_stub

from lib.publish import publish_generated  # noqa: E402

FAIL = 0


def fail(msg):
    global FAIL
    print(f"FAIL: {msg}", file=sys.stderr)
    FAIL = 1


def ok(msg):
    print(f"PASS: {msg}")


# t1: producer invoked and output written to target
with tempfile.TemporaryDirectory() as td:
    feat = os.path.join(td, "feature")
    root = os.path.join(td, "repo")
    os.makedirs(feat)
    os.makedirs(root)
    r = publish_generated(
        "CLAUDE.md",
        "generate-claude-md",
        {"policy_source": ".claude/features/policy/"},
        feature_dir=feat,
        repo_root=root,
    )
    target = os.path.join(root, "CLAUDE.md")
    if not r.passed:
        fail(f"t1: publish_generated failed: {r.messages}")
    elif not os.path.isfile(target):
        fail("t1: target file not created")
    elif open(target).read() != "# generated by generate-claude-md\n":
        fail(f"t1: target content mismatch: {open(target).read()!r}")
    else:
        ok("t1: producer invoked and output written to target")

# t2: idempotent — same content reports no-op
with tempfile.TemporaryDirectory() as td:
    feat = os.path.join(td, "feature")
    root = os.path.join(td, "repo")
    os.makedirs(feat)
    os.makedirs(root)
    target = os.path.join(root, "CLAUDE.md")
    with open(target, "w") as f:
        f.write("# generated by generate-claude-md\n")
    r = publish_generated("CLAUDE.md", "generate-claude-md", {}, feature_dir=feat, repo_root=root)
    if not r.passed:
        fail(f"t2: idempotent call failed: {r.messages}")
    elif not any("no-op" in m.lower() for m in r.messages):
        fail(f"t2: idempotent should report no-op, got: {r.messages}")
    else:
        ok("t2: idempotent: same content returns no-op result")

# t3: drift — different existing content is overwritten
with tempfile.TemporaryDirectory() as td:
    feat = os.path.join(td, "feature")
    root = os.path.join(td, "repo")
    os.makedirs(feat)
    os.makedirs(root)
    target = os.path.join(root, "CLAUDE.md")
    with open(target, "w") as f:
        f.write("old content\n")
    r = publish_generated("CLAUDE.md", "generate-claude-md", {}, feature_dir=feat, repo_root=root)
    if not r.passed:
        fail(f"t3: drift update failed: {r.messages}")
    elif open(target).read() != "# generated by generate-claude-md\n":
        fail("t3: drift update did not replace content")
    else:
        ok("t3: drift: different existing content is overwritten")

# t4: producer name and args passed through correctly
call_log = []


def _logging_producer(name, args, feature_dir, repo_root):
    call_log.append({"name": name, "args": args})
    return "x"


_producers_stub.call_producer = _logging_producer
with tempfile.TemporaryDirectory() as td:
    feat = os.path.join(td, "feature")
    root = os.path.join(td, "repo")
    os.makedirs(feat)
    os.makedirs(root)
    publish_generated("CLAUDE.md", "my-producer", {"k": "v"}, feature_dir=feat, repo_root=root)
    if call_log and call_log[0]["name"] == "my-producer" and call_log[0]["args"] == {"k": "v"}:
        ok("t4: producer name and args passed through correctly")
    else:
        fail(f"t4: unexpected call log: {call_log}")

# t5: target parent directories created automatically
_producers_stub.call_producer = lambda name, args, feature_dir, repo_root: "content"
with tempfile.TemporaryDirectory() as td:
    feat = os.path.join(td, "feature")
    root = os.path.join(td, "repo")
    os.makedirs(feat)
    os.makedirs(root)
    r = publish_generated("a/b/c/output.md", "read-file", {}, feature_dir=feat, repo_root=root)
    if not r.passed:
        fail(f"t5: deep target failed: {r.messages}")
    elif not os.path.isfile(os.path.join(root, "a", "b", "c", "output.md")):
        fail("t5: deep target not created")
    else:
        ok("t5: target parent directories created automatically")

if FAIL:
    print("test-publish-generated: FAIL", file=sys.stderr)
    sys.exit(1)
print("test-publish-generated: all checks passed.")
