#!/usr/bin/env bash
# test-RABBIT-CAGE-14-refresh-inline.sh
# Tests that rbt-refresh.sh handles CLAUDE.md with inline policy (rabbit-policy-start/end)
# rather than @-import lines.
#
# Bug: rbt-refresh.sh greps CLAUDE.md for @-import lines only.
# When CLAUDE.md uses inline policy (start/end markers, no @-imports), rbt-refresh.sh
# exits silently after resetting the counter — no injection fires.
# rbt-session-init.sh already checks for the inline section first (correct behavior).
#
# t2 and t3 MUST FAIL against the current rbt-refresh.sh (RED state).
# They turn green only after rbt-refresh.sh is given the same inline-section logic.
#
# Critical lesson: do NOT use @-imports in the test CLAUDE.md — that was how t7 in
# test-RABBIT-CAGE-12-counter-reset.sh accidentally passed while missing this bug.
#
# R3-compliant: no interactive constructs, fully automated.

set -u

REPO_ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel 2>/dev/null)"
REFRESH_HOOK="$REPO_ROOT/.claude/features/rabbit-cage/hooks/rbt-refresh.sh"

FAILURES=0

ok() {
    echo "  PASS t$1: $2"
}

fail_t() {
    echo "  FAIL t$1: $2"
    FAILURES=$(( FAILURES + 1 ))
}

echo "test-RABBIT-CAGE-14-refresh-inline.sh"
echo ""

# t1: rbt-refresh.sh exists and is executable
if [ -f "$REFRESH_HOOK" ] && [ -x "$REFRESH_HOOK" ]; then
    ok 1 "rbt-refresh.sh exists and is executable"
else
    fail_t 1 "rbt-refresh.sh missing or not executable at $REFRESH_HOOK"
fi

# Set up a temporary RABBIT_ROOT to isolate the test
TMPROOT="$(mktemp -d)"
trap 'rm -rf "$TMPROOT"' EXIT

THRESHOLD="${RBT_REFRESH_EVERY:-20}"
COUNTER_FILE="$TMPROOT/.rbt-prompt-counter"

# Build a CLAUDE.md that uses ONLY inline policy (rabbit-policy-start/end markers).
# NO @-import lines. This matches the structure of the actual production CLAUDE.md.
cat > "$TMPROOT/CLAUDE.md" <<'CLAUDEMD'
# Rabbit Workflow — test header

<!-- rabbit-policy-start: generated by generate-claude-md.sh from .claude/features/policy/ — do not edit manually -->

# Philosophy

Machine First. Every state, metadata, interface, and artifact is designed for
machine consumption first.

# Coding Rules

Simplicity First. Minimum code that solves the problem. Nothing speculative.

<!-- rabbit-policy-end -->
CLAUDEMD

# Seed counter at the threshold so the next increment triggers injection
printf '%s\n' "$THRESHOLD" > "$COUNTER_FILE"

# t2: rbt-refresh.sh emits output containing 'additionalContext' when CLAUDE.md
#     uses inline policy (rabbit-policy-start/end, NO @-imports).
#     This MUST FAIL against the current rbt-refresh.sh because it only reads @-imports.
refresh_output=""
refresh_exit=0
refresh_output="$(RABBIT_ROOT="$TMPROOT" RBT_REFRESH_EVERY="$THRESHOLD" bash "$REFRESH_HOOK" 2>/dev/null)" \
    || refresh_exit=$?

if echo "$refresh_output" | grep -q 'additionalContext'; then
    ok 2 "rbt-refresh.sh emits 'additionalContext' with inline-policy CLAUDE.md"
else
    fail_t 2 "rbt-refresh.sh did NOT emit 'additionalContext' — it silently exited when CLAUDE.md has inline policy only (no @-imports); output: '$(echo "$refresh_output" | head -3)'"
fi

# t3: the emitted additionalContext contains content from the inline policy section.
#     Specifically checks for 'Machine First' which appears in the inline block above.
#     Fails if rbt-refresh.sh skips the inline section and emits nothing (or wrong content).
context=""
if echo "$refresh_output" | grep -q 'additionalContext'; then
    context="$(echo "$refresh_output" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('additionalContext', ''))
except Exception:
    pass
" 2>/dev/null)"
fi

if echo "$context" | grep -q 'Machine First'; then
    ok 3 "additionalContext contains 'Machine First' from inline policy section"
else
    fail_t 3 "additionalContext does not contain 'Machine First' — inline policy section was not injected (context: '$(echo "$context" | head -3)')"
fi

echo ""
echo "Results: $(( 3 - FAILURES )) passed, $FAILURES failed"

if [ "$FAILURES" -eq 0 ]; then
    echo "ALL TESTS PASSED"
    exit 0
else
    echo "$FAILURES TEST(S) FAILED"
    exit 1
fi
