#!/usr/bin/env bash
# generate-claude-md.sh — generate CLAUDE.md by inlining the four policy files.
#
# Produces CLAUDE.md content to stdout. The caller writes it to the target path.
# Source of truth: .claude/features/policy/{philosophy,spec-rules,coding-rules,workflow-rules}.md
#
# Usage:
#   generate-claude-md.sh                    # emit to stdout
#   generate-claude-md.sh --write [TARGET]   # write to TARGET/CLAUDE.md (default: REPO_ROOT)
#
# Version: 1.0.0
# Owner: rabbit-workflow team (rabbit-cage)
# Deprecation criterion: when Claude Code natively resolves @-imports for subagents.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${RABBIT_ROOT:-$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)}"
POLICY_DIR="$REPO_ROOT/.claude/features/policy"

WRITE_MODE=0
TARGET_ROOT="$REPO_ROOT"

while [ $# -gt 0 ]; do
  case "$1" in
    --write) WRITE_MODE=1; TARGET_ROOT="${2:-$REPO_ROOT}"; [ $# -gt 1 ] && shift; shift ;;
    *) echo "ERROR: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

ONE_LINER="# Rabbit Workflow — subagent-driven development; every feature touch must invoke the rabbit-feature-touch skill to advance the full TDD state machine before the user decides on each dispatch."

emit() {
  printf '%s\n' "$ONE_LINER"
  printf '\n'
  printf '<!-- rabbit-policy-start: generated by generate-claude-md.sh from .claude/features/policy/ — do not edit manually -->\n'
  printf '\n'
  for f in \
    "$POLICY_DIR/philosophy.md" \
    "$POLICY_DIR/spec-rules.md" \
    "$POLICY_DIR/coding-rules.md" \
    "$POLICY_DIR/workflow-rules.md"; do
    [ -f "$f" ] || { echo "ERROR: missing policy file: $f" >&2; exit 1; }
    cat "$f"
    printf '\n'
  done
  printf '<!-- rabbit-policy-end -->\n'
}

if [ "$WRITE_MODE" -eq 1 ]; then
  emit > "$TARGET_ROOT/CLAUDE.md"
  echo "generate-claude-md: wrote $TARGET_ROOT/CLAUDE.md" >&2
else
  emit
fi
